objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Sprint__c.object
<CustomObject>
    <description>If a project is broken down into multiple sprints this object should be used.</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Theme__c.object
<CustomObject>
    <description>A theme is a group of user stories which contribute to a common goal. It is the highest level of the user story hierarchy. On the other hand, an epic is a big user story that has to be divided into several user stories because it can&apos;t be completed within one sprint.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sprint where the User Story is planned.</description>
        <inlineHelpText>Sprint where the User Story is planned.</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>copado__Sprint__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A theme is a group of user stories which contribute to a common goal. It is the highest level of the user story hierarchy. On the other hand, an epic is a big user story that has to be divided into several user stories because it can&apos;t be completed within one sprint.</description>
        <inlineHelpText>A theme is a group of user stories which contribute to a common goal. It is the highest level of the user story hierarchy. On the other hand, an epic is a big user story that has to be divided into several user stories because it can&apos;t be completed within</inlineHelpText>
        <label>Theme</label>
        <referenceTo>copado__Theme__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Module__c.object
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUpdateUserStoryStatusForVsmFlow.cls
@IsTest
public class TestUpdateUserStoryStatusForVsmFlow {
    @testSetup static void setup() {      
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Copado Admin'];
        User user = new User(Alias = 'newUser', Email='newuser666@copadoAPOproduct.com',
                             EmailEncodingKey='UTF-8', LastName='Jeldrik', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = p.Id, FirstName='Jeldrik',
                             TimeZoneSidKey='America/Los_Angeles', UserName='newuser666@copadoAPOproduct.com');
        insert user;
        
        
        
        copado__Sprint__c mySprint2 = new copado__Sprint__c();
        mySprint2.Name = 'Sprint1';
        insert mySprint2;
        
        copado__Project__c project = TestDataFactory.createProject('Test');
        copado__Theme__c theme = TestDataFactory.createTheme('Test');
        Module__c module = TestDataFactory.createModule('Test');
        
        Id recordTypeIdUserStory = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('User Story').getRecordTypeId();
        copado__User_Story__c myUserStory = new copado__User_Story__c();
        myUserStory.copado__User_Story_Title__c = 'UserStoryTest1';
        myUserStory.copado__Status__c = 'Draft';
        myUserStory.copado__Project__c = project.Id;
        myUserStory.copado__Theme__c = theme.Id;
        myUserStory.Module__c = module.Id;
        myUserStory.RecordTypeId = recordTypeIdUserStory;
        insert myUserStory;
        
        PermissionSet permissionSet = [SELECT Id FROM PermissionSet WHERE Name='Scrum_Master'];
        System.runAs(user) {
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = permissionSet.Id, AssigneeId = user.Id);
            insert psa;
        }
        
    }
    
    @IsTest
    static void testUserStoryMovedToSprint() {
        copado__Sprint__c createdSprint = [SELECT Id FROM copado__Sprint__c WHERE Name = 'Sprint1'];
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        User user = [SELECT Id FROM user WHERE email = 'newuser666@copadoAPOproduct.com'];
        System.runAs(user) 
        {
            createdUserStory.copado__Sprint__c = createdSprint.Id;
            createdUserStory.Documentation_Completed__c = 'Completed';
            update createdUserStory;
        }
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Ready for Development', assertUserStory.copado__Status__c);
    }
    
    @IsTest
    static void testInvestigationMovedToSprint() {
        copado__Sprint__c createdSprint = [SELECT Id FROM copado__Sprint__c WHERE Name = 'Sprint1'];
        Id recordTypeIdInvestigation = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('Investigation').getRecordTypeId();
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        User user = [SELECT Id FROM user WHERE email = 'newuser666@copadoAPOproduct.com'];
        System.runAs(user) 
        {
            createdUserStory.copado__Sprint__c = createdSprint.Id;
            createdUserStory.RecordTypeId = recordTypeIdInvestigation;
            update createdUserStory;
        }
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Ready for Investigation', assertUserStory.copado__Status__c);
    }
    
    @IsTest
    static void testBugMovedToSprint() {
        copado__Sprint__c createdSprint = [SELECT Id FROM copado__Sprint__c WHERE Name = 'Sprint1'];
        Id recordTypeIdBug = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('Bug').getRecordTypeId();
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        User user = [SELECT Id FROM user WHERE email = 'newuser666@copadoAPOproduct.com'];
        System.runAs(user) 
        {
            createdUserStory.copado__Sprint__c = createdSprint.Id;
            createdUserStory.RecordTypeId = recordTypeIdBug;
            createdUserStory.Documentation_Completed__c = 'Completed';
            update createdUserStory;
        }
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Ready for Development', assertUserStory.copado__Status__c);
    }   
    
    @IsTest
    static void testBugMovedToSprintAndStatusChanged() {
        copado__Sprint__c createdSprint = [SELECT Id FROM copado__Sprint__c WHERE Name = 'Sprint1'];
        Id recordTypeIdBug = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('Bug').getRecordTypeId();
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        User user = [SELECT Id FROM user WHERE email = 'newuser666@copadoAPOproduct.com'];
        System.runAs(user) 
        {
            createdUserStory.copado__Sprint__c = createdSprint.Id;
            createdUserStory.RecordTypeId = recordTypeIdBug;
            createdUserStory.copado__Status__c = 'Completed';
            createdUserStory.Documentation_Completed__c = 'Completed';
            update createdUserStory;
        }
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Completed', assertUserStory.copado__Status__c);
    } 
}