objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>Documentation_Release_Notes__c</fullName>
        <label>Documentation Release Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installation_Link_in_Production__c</fullName>
        <label>Installation Link in Production</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Installation_Link_in_Sandbox__c</fullName>
        <label>Installation Link in Sandbox</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Visible_in_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible in Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__Planned_Date__c</fullName>
        <inlineHelpText>Planned date for Production environments</inlineHelpText>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Beta</fullName>
                </value>
                <value>
                    <fullName>Ready for Testing</fullName>
                </value>
                <value>
                    <fullName>Approved by QA</fullName>
                </value>
                <value>
                    <fullName>Rejected by QA</fullName>
                </value>
                <value>
                    <fullName>Ready for Release</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Version__c</fullName>
        <description>When a Promotion linked to this Release is merged into the Main Branch of the deployment flow, Copado will tag the Main Branch with this version number. This value is typically a major (e.g. v7), minor (v7.3) or patch (v7.3.2) release.</description>
        <inlineHelpText>When a Promotion linked to this Release is merged into the Main Branch of the deployment flow, Copado will tag the Main Branch with this version number. This value is typically a major (e.g. v7), minor (v7.3) or patch (v7.3.2) release.</inlineHelpText>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Copado_Package_installerTest.cls
@isTest
public class Copado_Package_installerTest {

    static testMethod void testGetAllReleaseRecords(){
        copado__Release__c release = TestDataFactory.createRelease('test copadopackage');
        release.Visible_in_Community__c=true;
        release.copado__Description__c ='Test Released';
        release.copado__Version__c ='1.0';
        release.Installation_Link_in_Sandbox__c ='https://test.salesforce.com/';
        release.Installation_Link_in_Production__c ='https://login.salesforce.com/';
        release.Documentation_Release_Notes__c ='Test Released Note';        
        release.copado__Planned_Date__c = system.today();
        release.copado__Status__c = 'Released';
        Insert release;
        Copado_Package_installer.getAllReleaseRecords();
    } 
}