objects/kugo2p__AdditionalProductDetail__c.object
<CustomObject>
    <description>Kugamon - Related object to Salesforce Product that handles Kugamon Product data points. Kugamon does not add fields to Product object. Set data points such as key Service designation, Kits/Bundles, and Tax information. Only one Additional Product Info record allowed for a given Salesforce Product.</description>
    <fields>
        <fullName>kugo2p__ReferenceProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Additional_Product_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Product Info</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Product Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__SalesOrder__c.object
<CustomObject>
    <description>Kugamon - Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Salesforce CPQ Quote</description>
        <inlineHelpText>Salesforce CPQ Quote</inlineHelpText>
        <label>Quote Number</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kuga_sub__GenerateRenewalOpportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether a Renewal Opportunity will be generated by this Order upon Order Approval or Order Release based on the presence of a Renewable Service.</description>
        <label>Generate Renewal Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>kuga_sub__GenerateSubscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether a Subscription will be generated by this Order upon Order Approval or Order Release based on if Order Service Lines’ underlying Product record has the Create Subscription field is Checked.</description>
        <inlineHelpText>Subscription record creation is based on if the underlying Product is set to Create Subscription.</inlineHelpText>
        <label>Generate Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>kuga_sub__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Renewal Opportunity.

The Renewal Opportunity is created along with the Contract, when an Order is Approved or Released and a Renewable Service is present.</description>
        <label>Renewal Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders (Renewal Opportunity Name)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__ContactBilling__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Billing</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__ContactBuying__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Buying</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__ContactShipping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Shipping</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SalesOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__RecordStatus__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <description>Valid Statuses are: Draft, Sent, Approved, Released, and Cancelled. Released Order status cannot be manually changed; use Status formula field instead. Cancelled Order status cannot be changed at all.</description>
        <inlineHelpText>Valid Statuses are: Draft, Sent, Approved, Released, and Cancelled. Released Order status cannot be manually changed; use Status formula field instead. Cancelled Order status cannot be changed at all.</inlineHelpText>
        <label>Record Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>kugo2p__Warehouse__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>SO-{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Value_Prop_ID__c</fullName>
        <label>Value Prop ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>kuga_sub__Renewable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Renewable Services are Auto-Added to Renewal Opportuntiy when an Order is Approved or Released, as per Kugamon Settings. 

Renewable Products are only Auto-Added to Renewal Opportuntiy if the Order also contains a Renewable Service.</description>
        <inlineHelpText>Renewable Services are Auto-Added to Renewal Opportuntiy when an Order is Approved or Released, as per Kugamon Settings. 

Renewable Products are only Auto-Added to Renewal Opportuntiy if the Order also contains a Renewable Service.</inlineHelpText>
        <label>Renewable</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestKugamonOrderTriggerHelper.cls
@isTest
public class TestKugamonOrderTriggerHelper {
    @isTest
    public static void unitTest(){      
         
        Account accObj = TestDataFactory.createAccount('UnitTest', 'EUR');
        insert accObj;
        
        Contact conObj = TestDataFactory.createContact(accObj.id,'TestKugamonOrderTriggerHelper');
        conObj.MailingStreet = 'E5';
        conObj.MailingCity = 'Bengalore';
        conObj.MailingState = 'Karnataka';
        conObj.MailingCountry = 'India';
        Insert conObj;        
    
         //Renewal Opportunity
        Opportunity renewalOpp = TestDataFactory.createOpportunity(accObj, ' 1EE', 'Renewal');
        renewalOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        insert renewalOpp;        
        
        SBQQ__Quote__c renewalQuote = TestDataFactory.createCPQuote(renewalOpp);
        renewalQuote.SBQQ__Primary__c = true;
        Insert renewalQuote;    
                
        //Expansion Opportunity
        Opportunity expansionOpp = TestDataFactory.createOpportunity(accObj, ' 1EE', 'Add-on');
        expansionOpp.Value_Prop_ID__c = 'Test';
        expansionOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Expansion').getRecordTypeId();
        insert expansionOpp;
        
        SBQQ__Quote__c expansionQuote = TestDataFactory.createCPQuote(expansionOpp);
        expansionQuote.SBQQ__Primary__c = true;
        Insert expansionQuote;    
        
        Test.startTest();
        
        Product2 prod = TestDataFactory.createProduct('Copado Standard Edition','Licenses ',null);
        prod.kuga_sub__Renewable__c = true;
        Insert prod;        
        
        //kugo2p__AdditionalProductDetail__c testProductDetail1 = new kugo2p__AdditionalProductDetail__c();
        //testProductDetail1.kugo2p__ReferenceProduct__c = prod.Id;
        //insert testProductDetail1;    
        
        SBQQ__QuoteLine__c renewalQLine = TestDataFactory.createCPQQuoteLine(renewalQuote.Id,prod.Id);
        insert renewalQLine;   
        
        Product2 prod2 = TestDataFactory.createProduct('Copado Admin','Licenses ',null);
        Insert prod2;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=prod2.Id, UnitPrice=5, IsActive=true,CurrencyIsoCode='EUR');
        insert standardPrice;    
        
        SBQQ__QuoteLine__c expansionQLine = TestDataFactory.createCPQQuoteLine(expansionQuote.Id,prod2.Id);
        Insert expansionQLine ;  
        
        Test.stopTest(); 
        
        Pricebook2 pb = TestDataFactory.createPricebook(); 
        pb.CurrencyIsoCode = 'EUR';
        insert pb;  
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(pb.name);       
        insert testKugamonSetting ;     
        
        kugo2p__Warehouse__c wareObj = TestDataFactory.createWarehouse('test',testKugamonSetting.id);
        Insert wareObj;
        
        kugo2p__SalesOrder__c orderObj = TestDataFactory.createKugamonOrder(accObj.id);
        orderObj.kugo2p__ContactBilling__c = conObj.id;
        orderObj.kugo2p__ContactBuying__c = conObj.id;
        orderObj.kugo2p__ContactShipping__c = conObj.id;
        orderObj.kugo2p__Warehouse__c = wareObj.Id;        
        orderObj.RecordTypeId = Schema.SObjectType.kugo2p__SalesOrder__c.getRecordTypeInfosByName().get('Expansion').getRecordTypeId();
        orderObj.kuga_sub__GenerateSubscription__c = true;        
        orderObj.kuga_sub__GenerateRenewalOpportunity__c =true;
        Insert orderObj;
        orderObj.Quote__c = expansionQuote.Id;
        orderObj.kugo2p__Opportunity__c = expansionOpp.Id;
        orderObj.kuga_sub__RenewalOpportunity__c = renewalOpp.Id;
        orderObj.kugo2p__RecordStatus__c = 'Released';       
        List<kugo2p__SalesOrder__c> orderList = new List<kugo2p__SalesOrder__c>();
        orderList.add(orderObj);
        KugamonOrderTriggerHelper.createQuoteLineOnRenewalOpportuntiy(orderList);
        //Update orderObj;               
    }    
}