objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ACV__c</fullName>
        <label>ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MRR__c</fullName>
        <label>MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TCV__c</fullName>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>ACV__c</fullName>
        <label>ACV</label>
        <summarizedField>SBQQ__QuoteLine__c.Annualized_ACV__c</summarizedField>
        <summaryFilterItems>
            <field>SBQQ__QuoteLine__c.ACV_ARR_Product__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Current_License_TCV__c</fullName>
        <description>Shows the License value for the current contract at the moment of Quote creation and update. Calculated upon amendment quote creation or amendment quote date updates.</description>
        <inlineHelpText>Shows the License value for the current contract at the moment of Quote creation and update. Calculated upon amendment quote creation or amendment quote date updates.</inlineHelpText>
        <label>Current License TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Months__c</fullName>
        <description>Indicates the number of months for a quote. Calculated upon quote creation and changes of quote start/end dates.</description>
        <inlineHelpText>Indicates the number of months for a quote. Calculated upon quote creation and changes of quote start/end dates.</inlineHelpText>
        <label>Number of Months</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remaining_License_TCV__c</fullName>
        <description>This field is used to calculate the Premier Support costs of the remaining TCV on the account.</description>
        <label>Remaining License TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master contract with which subscription products in this quote are to be co-terminated.</description>
        <inlineHelpText>Master contract with which subscription products in this quote are to be co-terminated.</inlineHelpText>
        <label>Master Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.SBQQ__Evergreen__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Co-Terminated Quotes</relationshipLabel>
        <relationshipName>CoTerminatedQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TCV__c</fullName>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__DefaultSubscriptionTerm__c</fullName>
        <description>Term length of the subscription, which only applies if the product is a subscription. It is copied from the Subscription Term of the related product when the line item is first generated.</description>
        <inlineHelpText>Term length of the subscription, which only applies if the product is a subscription. It is copied from the Subscription Term of the related product when the line item is first generated.</inlineHelpText>
        <label>Default Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
        <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
        <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net unit price for the product quoted by this line item.</description>
        <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
        <label>Net Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__PackageTotal__c</fullName>
        <description>Total price of this package including its components.</description>
        <formula>SBQQ__ComponentTotal__c + SBQQ__NetTotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total price of this package including its components.</inlineHelpText>
        <label>Package Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductFamily__c</fullName>
        <description>How you would categorize/group/organize this within Salesforce (whether it&apos;s a new or existing Product Family). Additionally, this field can be used during product selection to filter to the correct product or product SKU.</description>
        <formula>TEXT(SBQQ__Product__r.Family)</formula>
        <inlineHelpText>How you would categorize/group/organize this within Salesforce (whether it&apos;s a new or existing Product Family). Additionally, this field can be used during product selection to filter to the correct product or product SKU.</inlineHelpText>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProrateMultiplier__c</fullName>
        <description>Calculated ratio used to compute Prorated Price.</description>
        <inlineHelpText>Calculated ratio used to compute Prorated Price.</inlineHelpText>
        <label>Prorate Multiplier</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>The last date this contract is valid.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionEndDate__c), SBQQ__Contract__r.EndDate, SBQQ__SubscriptionEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The last date this contract is valid.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List price for this subscription product.</description>
        <inlineHelpText>List price for this subscription product.</inlineHelpText>
        <label>List Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net price for this subscription.</description>
        <inlineHelpText>Net price for this subscription.</inlineHelpText>
        <label>Net Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProrateMultiplier__c</fullName>
        <description>Calculated ratio used to compute prorated price.</description>
        <inlineHelpText>Calculated ratio used to compute prorated price.</inlineHelpText>
        <label>Prorate Multiplier</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>The first date this subscription is in effect.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionStartDate__c), SBQQ__Contract__r.StartDate, SBQQ__SubscriptionStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The first date this subscription is in effect.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPQQuoteTriggerHelper.cls
public class CPQQuoteTriggerHelper {

    private static Set<Id> lstQuoteIds = new Set<Id>();
    private static Map<Id, SBQQ__Quote__c> mapQuote = new Map<Id, SBQQ__Quote__c>();
    private static Map<Id, List<SBQQ__Subscription__c>> contractSubscriptionMap = new Map<Id, List<SBQQ__Subscription__c>>();
    
    public static void prepareDataBefore(List<SObject> records) {
        Set<Id> contractIds = new Set<Id>();
        for (SObject so : records) {
            SBQQ__Quote__c q = (SBQQ__Quote__c)so;
            contractIds.add(q.SBQQ__MasterContract__c);
            contractSubscriptionMap.put(q.SBQQ__MasterContract__c, new List<SBQQ__Subscription__c>());
        }
        for(SBQQ__Subscription__c s : getCPQSubscriptions(contractIds)){
            List<SBQQ__Subscription__c> tmp = contractSubscriptionMap.get(s.SBQQ__Contract__c);
            tmp.add(s);
            contractSubscriptionMap.put(s.SBQQ__Contract__c, tmp);
        }
    }
    public static void prepareDataAfter(List<SObject> records) {
        for (SObject so : records) {
            SBQQ__Quote__c q = (SBQQ__Quote__c)so;
            if (q.SBQQ__Primary__c && string.isNotEmpty(q.SBQQ__Opportunity2__c)) {
                lstQuoteIds.add(q.Id);
            }
        }
        system.debug('@@@ result size: '+lstQuoteIds.size());
        if(lstQuoteIds.size()>0){
            mapQuote = new CPQQuoteSelector().GetQuoteById(lstQuoteIds);
            system.debug('@@@ map quote size: '+mapQuote.keySet().size());
        }
    }
    
    public static void setAcvTcvOnOpportunities(){
        
        List<Opportunity> lstOpps = new List<Opportunity>();
        for (SBQQ__Quote__c q : mapQuote.values()) {
            
            Decimal dTotalACV = 0;
            Decimal dTotalTCV = 0;
            Decimal dTotalMRR = 0;
            for (SBQQ__QuoteLine__c ql : q.SBQQ__LineItems__r) {
                if((ql.SBQQ__ProductFamily__c=='Licenses' || ql.SBQQ__ProductFamily__c=='Premier Support') && ql.SBQQ__ProrateMultiplier__c!=null && ql.SBQQ__DefaultSubscriptionTerm__c!=null){
                    dTotalTCV += ql.SBQQ__PackageTotal__c;
                    dTotalMRR += (ql.SBQQ__PackageTotal__c/q.Number_of_Months__c);
                    if ((ql.SBQQ__DefaultSubscriptionTerm__c * ql.SBQQ__ProrateMultiplier__c) < 12) {
                        dTotalACV += ql.SBQQ__PackageTotal__c;
                    }
                    else {
                        dTotalACV += ql.SBQQ__PackageTotal__c * (12 / (ql.SBQQ__DefaultSubscriptionTerm__c * ql.SBQQ__ProrateMultiplier__c));
                    }    
                }
            }

            // Add the opp to the list to update
            lstOpps.add(new Opportunity(Id=q.SBQQ__Opportunity2__c, TCV__c=dTotalTCV, ACV__c=dTotalACV, MRR__c=dTotalMRR));
        }
        // Update the opps
        if (lstOpps.size() > 0) {
            system.debug('### Updateing opportunities: '+lstOpps.size());
            // SG 2019-12-23: Deprecating code tranistining logic to price rules - need the above code for code coverage
            //update lstOpps;
        }
        
    }
    
    public static void setNumberOfMonths(SBQQ__Quote__c quote){
        if(quote.SBQQ__StartDate__c!=null && quote.SBQQ__EndDate__c!=null){
            Decimal proration = CPQMigrationHelper.calculateProRate(quote.SBQQ__StartDate__c, quote.SBQQ__EndDate__c);
            quote.Number_of_Months__c = proration;
        }
    }
    public static void setRemainingLicenseTCV(SBQQ__Quote__c oldQuote, SBQQ__Quote__c newQuote){
        // if is new quote and not been ammended, enter if statement.
        if(oldQuote!=null){
            system.debug('### OldQuote is null: ');
            if (!datesHaveChanged(oldQuote, newQuote)) return;
        }
        if (!isAmendmentQuote(newQuote)) return;
        
        system.debug('### Entering setRemainingLicenseTCV: StartDate='+newQuote.SBQQ__StartDate__c+'; EndDate='+newQuote.SBQQ__EndDate__c);
        Decimal proration = CPQMigrationHelper.calculateProRate(newQuote.SBQQ__StartDate__c, newQuote.SBQQ__EndDate__c);
        system.debug('### Proration calculated: '+ proration);
        
        system.debug('### MasterContract: '+newQuote.SBQQ__MasterContract__c);
        //get license subscription items
        List<SBQQ__Subscription__c> subscriptions = contractSubscriptionMap.get(newQuote.SBQQ__MasterContract__c);
        if(subscriptions == null)return;
        
        //calculate license value per month for subscriptions
        Decimal monthlyValue = 0;
        Decimal fullValue = 0;
        for(SBQQ__Subscription__c sub : subscriptions){
            fullValue += sub.SBQQ__NetPrice__c * sub.SBQQ__Quantity__c;
            monthlyValue += (sub.SBQQ__NetPrice__c * sub.SBQQ__Quantity__c)/sub.SBQQ__ProrateMultiplier__c;
        }

        //calculate remaining TCV
        System.debug('actual TCV - proration: ' + proration + ' ; licenseValue: ' + monthlyValue);

        Decimal remainingTCV = monthlyValue * proration;
        newQuote.Remaining_License_TCV__c = remainingTCV;
        newQuote.Current_License_TCV__c = fullValue;
    }
    public static void deleteSchedules() {
        
        List<OpportunityLineItemSchedule> scheds = [select Id from OpportunityLineItemSchedule where
                                                   OpportunityLineItem.SBQQ__QuoteLine__r.SBQQ__Quote__c IN :lstQuoteIds and
                                                   OpportunityLineItem.Product2.CanUseRevenueSchedule=true and
                                                   OpportunityLineItem.Product2.IsActive=true];
        system.debug('Schedules records to be deleted: '+scheds.size());
        delete scheds;
    }
    
    private static List<SBQQ__Subscription__c> getCPQSubscriptions(Set<Id> cids){
        List<SBQQ__Subscription__c> subs = [SELECT Id, Name, SBQQ__ListPrice__c, SBQQ__NetPrice__c, SBQQ__Quantity__c, SBQQ__ProrateMultiplier__c, SBQQ__Contract__c
                FROM SBQQ__Subscription__c
                WHERE SBQQ__Contract__c IN :cids
                AND SBQQ__Product__r.Family = 'Licenses'];
        return subs;
    }
    private static Boolean isAmendmentQuote(SBQQ__Quote__c quote){
        system.debug('### Entering isAmendmentQuote: quote='+quote);
        if(quote.SBQQ__Type__c == 'Amendment' && quote.SBQQ__MasterContract__c != null){
            system.debug('### isAmendmentQuote: return true;');
            return true;
        } else {
            system.debug('### isAmendmentQuote: return false;');
            return false;
        }
    }
    private static Boolean datesHaveChanged(SBQQ__Quote__c oldQuote, SBQQ__Quote__c newQuote){
        system.debug('### Entering datesHaveChanged: oldQuote='+oldQuote+'; newQuote='+newQuote);
        if(newQuote.SBQQ__StartDate__c != oldQuote.SBQQ__StartDate__c || newQuote.SBQQ__EndDate__c != oldQuote.SBQQ__EndDate__c){
            system.debug('### datesHaveChanged: return true;');
            return true;
        } else{
            system.debug('### datesHaveChanged: return false;');
            return false;
        }
    }
    
}