objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>OriginalQuoteLineId2__c</fullName>
        <label>OriginalQuoteLineId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__AllowAssetRefund__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the underlying asset may have its quantity refunded. Only relevant for Amendments.</description>
        <inlineHelpText>Indicates whether the asset represented by this line may be refunded.</inlineHelpText>
        <label>Allow Asset Refunds</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProrateMultiplier__c</fullName>
        <description>Calculated ratio used to compute Prorated Price.</description>
        <inlineHelpText>Calculated ratio used to compute Prorated Price.</inlineHelpText>
        <label>Prorate Multiplier</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ScheduleProductinQuoteLines.cls
//This scheduler class will map Renewal QuoteLines with Product and run in every 10 minutes.
global class ScheduleProductinQuoteLines implements Schedulable {
   
    global void execute(SchedulableContext sc) {       
       
        // process each batch of records default size is 200
        Map<string,SBQQ__QuoteLine__c> origQuoteLineIdAndQuoteLine = new Map<string,SBQQ__QuoteLine__c>();
        List<SBQQ__QuoteLine__c> updateQuoteLineList = new List<SBQQ__QuoteLine__c>();
        
        List<SBQQ__QuoteLine__c> qtLineList = [SELECT Id, SBQQ__AllowAssetRefund__c,SBQQ__Quote__c,OriginalQuoteLineId2__c FROM SBQQ__QuoteLine__c where SBQQ__Product__c = null AND  OriginalQuoteLineId2__c != null];
        IF(Test.isRunningTest()){
            qtLineList = [SELECT Id, SBQQ__AllowAssetRefund__c,SBQQ__Quote__c,OriginalQuoteLineId2__c FROM SBQQ__QuoteLine__c where OriginalQuoteLineId2__c != null];
        }
        for(SBQQ__QuoteLine__c quoteLine : qtLineList) {
            
            origQuoteLineIdAndQuoteLine.put(quoteLine.OriginalQuoteLineId2__c,quoteLine);  
            
        }   
       
        if(!origQuoteLineIdAndQuoteLine.isEmpty()) {
            for(SBQQ__QuoteLine__c originalQuoteLine : [Select Id, SBQQ__ProrateMultiplier__c,SBQQ__Product__c from SBQQ__QuoteLine__c where Id IN:origQuoteLineIdAndQuoteLine.keySet()]) {
                origQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__Product__c = originalQuoteLine.SBQQ__Product__c;
                origQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ProrateMultiplier__c = originalQuoteLine.SBQQ__ProrateMultiplier__c;
                origQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__AllowAssetRefund__c = true;
                updateQuoteLineList.add(origQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id));
            }
        }

        if(!updateQuoteLineList.isEmpty()) {               
            try {           
                update updateQuoteLineList;
            
            } catch(Exception e) {
                System.debug(e);
            }    
        }         
    }  
}